"""init

Revision ID: fd5d3cd3cb2e
Revises: 
Create Date: 2020-11-05 19:16:39.251171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5d3cd3cb2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_version',
    sa.Column('proposal_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('participant_number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('personnel_cost', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('subcontracting_cost', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('other_direct_costs', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('proposal_related_text', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_coordinator', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('proposal_id', 'company_id', 'transaction_id')
    )
    op.create_index(op.f('ix_association_version_end_transaction_id'), 'association_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_association_version_operation_type'), 'association_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_association_version_transaction_id'), 'association_version', ['transaction_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('company_type', sa.String(length=256), nullable=True),
    sa.Column('specialisation', sa.String(length=256), nullable=True),
    sa.Column('pic', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email'),
    sa.UniqueConstraint('pic')
    )
    op.create_index(op.f('ix_company_acronym'), 'company', ['acronym'], unique=True)
    op.create_index(op.f('ix_company_country'), 'company', ['country'], unique=False)
    op.create_table('deliverable_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('responsible', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('due_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('dissemination_level', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('wp_reference', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_deliverable_version_end_transaction_id'), 'deliverable_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_deliverable_version_operation_type'), 'deliverable_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_deliverable_version_transaction_id'), 'deliverable_version', ['transaction_id'], unique=False)
    op.create_table('milestone_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('responsible', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('due_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('wp_reference', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_milestone_version_end_transaction_id'), 'milestone_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_milestone_version_operation_type'), 'milestone_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_milestone_version_transaction_id'), 'milestone_version', ['transaction_id'], unique=False)
    op.create_table('proposal_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('acronym', sa.String(length=64), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('budget', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('duration_months', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('action_type', sa.String(length=512), autoincrement=False, nullable=True),
    sa.Column('indirect_costs_rate', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('call', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('topic', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_proposal_version_acronym'), 'proposal_version', ['acronym'], unique=False)
    op.create_index(op.f('ix_proposal_version_end_transaction_id'), 'proposal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_proposal_version_operation_type'), 'proposal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_proposal_version_transaction_id'), 'proposal_version', ['transaction_id'], unique=False)
    op.create_table('proposalstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('badge_type', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposalstatus_status'), 'proposalstatus', ['status'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('surname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('trello_token', sa.String(length=64), nullable=True),
    sa.Column('trello_api_key', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('wp_company_version',
    sa.Column('WP_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('person_month', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('leader', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('WP_id', 'company_id', 'transaction_id')
    )
    op.create_index(op.f('ix_wp_company_version_end_transaction_id'), 'wp_company_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_wp_company_version_operation_type'), 'wp_company_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_wp_company_version_transaction_id'), 'wp_company_version', ['transaction_id'], unique=False)
    op.create_table('wp_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=256), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('start_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('end_month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('proposal_reference', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_wp_version_end_transaction_id'), 'wp_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_wp_version_operation_type'), 'wp_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_wp_version_transaction_id'), 'wp_version', ['transaction_id'], unique=False)
    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('action_type', sa.String(length=512), nullable=True),
    sa.Column('indirect_costs_rate', sa.Float(), nullable=True),
    sa.Column('call', sa.String(length=256), nullable=True),
    sa.Column('topic', sa.String(length=256), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['proposalstatus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_acronym'), 'proposal', ['acronym'], unique=True)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_table('association',
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('participant_number', sa.Integer(), nullable=True),
    sa.Column('personnel_cost', sa.Float(), nullable=True),
    sa.Column('subcontracting_cost', sa.Float(), nullable=True),
    sa.Column('other_direct_costs', sa.Float(), nullable=True),
    sa.Column('proposal_related_text', sa.Text(), nullable=True),
    sa.Column('is_coordinator', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('proposal_id', 'company_id')
    )
    op.create_table('to_do',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('proposal_reference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['proposal_reference'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_proposal',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'proposal_id')
    )
    op.create_table('wp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_month', sa.Integer(), nullable=True),
    sa.Column('end_month', sa.Integer(), nullable=True),
    sa.Column('proposal_reference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_reference'], ['proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deliverable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('responsible', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_month', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('dissemination_level', sa.String(length=256), nullable=True),
    sa.Column('wp_reference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wp_reference'], ['wp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('responsible', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_month', sa.Integer(), nullable=True),
    sa.Column('wp_reference', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wp_reference'], ['wp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wp_company',
    sa.Column('WP_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('person_month', sa.Float(), nullable=True),
    sa.Column('leader', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['WP_id'], ['wp.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('WP_id', 'company_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wp_company')
    op.drop_table('milestone')
    op.drop_table('deliverable')
    op.drop_table('wp')
    op.drop_table('user_proposal')
    op.drop_table('to_do')
    op.drop_table('association')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_proposal_acronym'), table_name='proposal')
    op.drop_table('proposal')
    op.drop_index(op.f('ix_wp_version_transaction_id'), table_name='wp_version')
    op.drop_index(op.f('ix_wp_version_operation_type'), table_name='wp_version')
    op.drop_index(op.f('ix_wp_version_end_transaction_id'), table_name='wp_version')
    op.drop_table('wp_version')
    op.drop_index(op.f('ix_wp_company_version_transaction_id'), table_name='wp_company_version')
    op.drop_index(op.f('ix_wp_company_version_operation_type'), table_name='wp_company_version')
    op.drop_index(op.f('ix_wp_company_version_end_transaction_id'), table_name='wp_company_version')
    op.drop_table('wp_company_version')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_proposalstatus_status'), table_name='proposalstatus')
    op.drop_table('proposalstatus')
    op.drop_index(op.f('ix_proposal_version_transaction_id'), table_name='proposal_version')
    op.drop_index(op.f('ix_proposal_version_operation_type'), table_name='proposal_version')
    op.drop_index(op.f('ix_proposal_version_end_transaction_id'), table_name='proposal_version')
    op.drop_index(op.f('ix_proposal_version_acronym'), table_name='proposal_version')
    op.drop_table('proposal_version')
    op.drop_index(op.f('ix_milestone_version_transaction_id'), table_name='milestone_version')
    op.drop_index(op.f('ix_milestone_version_operation_type'), table_name='milestone_version')
    op.drop_index(op.f('ix_milestone_version_end_transaction_id'), table_name='milestone_version')
    op.drop_table('milestone_version')
    op.drop_index(op.f('ix_deliverable_version_transaction_id'), table_name='deliverable_version')
    op.drop_index(op.f('ix_deliverable_version_operation_type'), table_name='deliverable_version')
    op.drop_index(op.f('ix_deliverable_version_end_transaction_id'), table_name='deliverable_version')
    op.drop_table('deliverable_version')
    op.drop_index(op.f('ix_company_country'), table_name='company')
    op.drop_index(op.f('ix_company_acronym'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_association_version_transaction_id'), table_name='association_version')
    op.drop_index(op.f('ix_association_version_operation_type'), table_name='association_version')
    op.drop_index(op.f('ix_association_version_end_transaction_id'), table_name='association_version')
    op.drop_table('association_version')
    # ### end Alembic commands ###
